-- Migration: 01_create_motion_graphics  (STAGED — feature-local ordinal)
-- (staged under docs/features/ai-motion-graphic/migrations/ — `implement` promotes
--  this to apps/api/src/db/migrations/058_create_motion_graphics.sql. Live tree is at
--  057_*; `implement` assigns the real number at promote-time in case another feature
--  promotes first.)
--
-- The aggregate-root table for a Motion Graphic (ADR-0008): a per-Creator, code-backed
-- media asset whose content is component code stored as TEXT in the DB (not an S3 blob).
-- Read with the record on every open/preview (SAD §6 flow 4) and listed per-owner
-- (flow 5 / AC-13). A typed props schema (shape-only, MVP1) and a version-capable shape
-- are laid in from day one so MVP2 prop-forms + MVP3 version-pinning add additively
-- (spec §2 goal 3, ADR-0008).
--
-- Column notes:
--   id              — UUID v4, generated by the application layer (randomUUID()).
--   user_id         — FK to users.user_id; the owning Creator. Every read/write is
--                     filtered by this (AC-07 uniform-not-exist, AC-13 list-mine).
--   title           — auto-generated on create, renamable by the Creator (AC-01).
--   code            — current ready component code (ADR-0008). NULL until the first
--                     successful generation; on a failed first attempt the row may exist
--                     with NULL code (AC-06). On refine, stays the last working code
--                     when a new attempt fails (AC-14).
--   props_schema    — typed props schema, SHAPE ONLY in MVP1 (no validation/forms yet);
--                     untyped JSON, app-owned shape (precedent: user_settings.settings_json
--                     050, generation_flows.canvas 046). Forward-compat for MVP2.
--   duration_seconds— the fixed animation length the Creator sets via the duration input
--                     (AC-01); DECIMAL(6,2) allows fractional seconds (e.g. 2.50 s).
--                     Remotion durationInFrames = round(duration_seconds * fps).
--   fps / width /   — the runtime geometry the graphic authors against (ADR-0008);
--   height            defaults match the repo's Remotion composition norms.
--   runtime_version — the pinned Remotion runtime the graphic was authored against
--                     (ADR-0010); the hook a later milestone uses for re-validation.
--   status          — ready-state machine (glossary "Ready state"): 'generating' while a
--                     run is in flight, 'ready' only when the code both runs in preview AND
--                     meets the deterministic-render rule (AC-06/AC-09), 'failed' when the
--                     attempt did not produce a usable graphic. Only 'ready' can be attached
--                     (AC-08).
--   version         — version-capable hook (ADR-0008): increments on each successful code
--                     update; the snapshot records which version it froze (MVP3 pinning).
--                     Mirrors generation_flows.version (046).
--   created_at /    — repo audit convention (DATETIME(3), ON UPDATE for updated_at;
--   updated_at        precedent 046/050/057).
--   deleted_at      — soft-delete (repo norm; precedent generation_flows 046, files);
--                     the list query filters deleted_at IS NULL.
--
-- Idempotent: CREATE TABLE IF NOT EXISTS.
--
-- Manual rollback:
--   DROP TABLE IF EXISTS motion_graphics;

CREATE TABLE IF NOT EXISTS motion_graphics (
  id                CHAR(36)      NOT NULL,
  user_id           CHAR(36)      NOT NULL,
  title             VARCHAR(255)  NOT NULL DEFAULT 'Untitled motion graphic',
  code              MEDIUMTEXT    NULL,
  props_schema      JSON          NULL,
  duration_seconds  DECIMAL(6,2)  NOT NULL,
  fps               INT UNSIGNED  NOT NULL DEFAULT 30,
  width             INT UNSIGNED  NOT NULL DEFAULT 1920,
  height            INT UNSIGNED  NOT NULL DEFAULT 1080,
  runtime_version   VARCHAR(32)   NOT NULL DEFAULT '4.0.443',
  status            ENUM(
                      'generating',
                      'ready',
                      'failed'
                    )             NOT NULL DEFAULT 'generating',
  version           INT UNSIGNED  NOT NULL DEFAULT 1,
  created_at        DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at        DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
                                  ON UPDATE CURRENT_TIMESTAMP(3),
  deleted_at        DATETIME(3)   NULL     DEFAULT NULL,

  PRIMARY KEY (id),
  -- Serves the only non-PK query: list my active graphics newest-first
  -- (flow 5 / AC-13: WHERE user_id=? AND deleted_at IS NULL ORDER BY updated_at DESC).
  -- Leading user_id also satisfies the fk_motion_graphics_user FK-index requirement.
  KEY idx_motion_graphics_user_active (user_id, deleted_at, updated_at DESC),

  CONSTRAINT fk_motion_graphics_user
    FOREIGN KEY (user_id)
    REFERENCES users(user_id)
    ON DELETE CASCADE
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;
