-- Migration: 02_create_motion_graphic_chat_turns  (STAGED — feature-local ordinal)
-- (staged under docs/features/ai-motion-graphic/migrations/ — `implement` promotes this
--  to apps/api/src/db/migrations/059_create_motion_graphic_chat_turns.sql. The real number
--  is assigned at promote-time, in this ordinal order, after 01_create_motion_graphics.)
--
-- The persistent, never-deleted chat history of a Motion Graphic (SAD §8 "Chat history";
-- AC-03 append, AC-12 duplicate-as-live-turns, AC-14 record-failed-attempt). Each turn is
-- a re-runnable exchange, not a frozen transcript: an assistant turn stores the code it
-- produced, so duplicate (AC-12) can seed the copy with live, re-runnable turns plus the
-- current code.
--
-- Column notes:
--   id                — UUID v4, generated by the application layer.
--   motion_graphic_id — FK to motion_graphics.id; the owning graphic. ON DELETE CASCADE
--                       (a soft-deleted graphic keeps its turns; a hard delete removes them).
--   role              — who authored the turn: 'user' (the Creator's instruction) or
--                       'assistant' (the AI's reply).
--   seq               — monotonic per-graphic order (app-assigned). Explicit ordering so a
--                       duplicate can copy turns in exact order (created_at(3) ties are
--                       possible on a bulk copy insert). Mirrors the app-controlled
--                       sort_order idiom (storyboard_block_media 033).
--   content           — the message text: the user's instruction, or the assistant's
--                       plain-language reply. MEDIUMTEXT (LLM replies can be long).
--   generated_code    — the component code an assistant turn produced (NULL for user turns
--                       and for assistant turns that failed to produce code). Makes the turn
--                       re-runnable (AC-12).
--   outcome           — for assistant turns: 'ready' (ran in preview AND deterministic) or
--                       'failed' (did not produce a usable graphic). NULL for user turns.
--                       Records the failed attempt without overwriting the graphic (AC-14).
--   error_message     — plain-language failure text for a failed assistant turn (AC-14);
--                       VARCHAR(512) matches the job-table convention (037/052/057).
--   created_at        — repo audit convention. No updated_at: turns are append-only/immutable.
--
-- Idempotent: CREATE TABLE IF NOT EXISTS.
--
-- Manual rollback:
--   DROP TABLE IF EXISTS motion_graphic_chat_turns;

CREATE TABLE IF NOT EXISTS motion_graphic_chat_turns (
  id                 CHAR(36)     NOT NULL,
  motion_graphic_id  CHAR(36)     NOT NULL,
  role               ENUM(
                       'user',
                       'assistant'
                     )            NOT NULL,
  seq                INT UNSIGNED NOT NULL,
  content            MEDIUMTEXT   NOT NULL,
  generated_code     MEDIUMTEXT   NULL,
  outcome            ENUM(
                       'ready',
                       'failed'
                     )            NULL DEFAULT NULL,
  error_message      VARCHAR(512) NULL,
  created_at         DATETIME(3)  NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

  PRIMARY KEY (id),
  -- Serves: read a graphic's chat in order (flows 3/4/6: WHERE motion_graphic_id=?
  -- ORDER BY seq) and the duplicate copy-read (AC-12). Leading motion_graphic_id also
  -- satisfies the fk_mg_chat_turns_graphic FK-index requirement.
  KEY idx_mg_chat_turns_graphic_seq (motion_graphic_id, seq),

  CONSTRAINT fk_mg_chat_turns_graphic
    FOREIGN KEY (motion_graphic_id)
    REFERENCES motion_graphics(id)
    ON DELETE CASCADE
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;
