-- Migration: 03_create_motion_graphic_block_snapshots  (STAGED — feature-local ordinal)
-- (staged under docs/features/ai-motion-graphic/migrations/ — `implement` promotes this to
--  apps/api/src/db/migrations/060_create_motion_graphic_block_snapshots.sql. Real number at
--  promote-time; created BEFORE 04 because storyboard_block_media's new FK references it.)
--
-- The immutable, frozen snapshot of a Motion Graphic at the moment it is attached to a
-- storyboard block (ADR-0009). A placed instance is a frozen copy of code + duration, never
-- a live reference — a later refinement of the source graphic (flow 3) cannot alter a placed
-- instance (AC-10). Kept in its own table (not polymorphic columns on the pivot) so the
-- immutable snapshot has a clean, isolated lifecycle and version-pinning (MVP3) has a home.
--
-- Column notes:
--   id                       — UUID v4, generated by the application layer.
--   source_motion_graphic_id — FK to motion_graphics.id; the graphic this was snapshotted
--                              from. ON DELETE SET NULL (NOT cascade): the frozen instance
--                              must survive deletion of its source (AC-10 — independent of
--                              the source). Hence NULLABLE.
--   code                     — frozen component code at attach time (AC-04). NOT NULL: only a
--                              ready graphic with working code can be attached (AC-08).
--   props_schema             — frozen props-schema snapshot (shape-only MVP1); forward-compat
--                              for MVP2 per-instance prop values.
--   duration_seconds         — frozen duration at attach (AC-04); DECIMAL(6,2), mirrors
--                              motion_graphics.duration_seconds.
--   fps / width / height     — frozen runtime geometry, so the future server export renders
--                              the instance exactly as previewed.
--   runtime_version          — the pinned Remotion runtime the snapshot froze against
--                              (ADR-0010); snapshot is taken WITHOUT re-validation.
--   source_version           — which motion_graphics.version was frozen (version-pinning
--                              hook, MVP3); NULL-safe if the source row is later gone.
--   created_at               — attach timestamp. No updated_at: a snapshot is immutable by
--                              convention.
--
-- Idempotent: CREATE TABLE IF NOT EXISTS.
--
-- Manual rollback:
--   DROP TABLE IF EXISTS motion_graphic_block_snapshots;

CREATE TABLE IF NOT EXISTS motion_graphic_block_snapshots (
  id                        CHAR(36)      NOT NULL,
  source_motion_graphic_id  CHAR(36)      NULL,
  code                      MEDIUMTEXT    NOT NULL,
  props_schema              JSON          NULL,
  duration_seconds          DECIMAL(6,2)  NOT NULL,
  fps                       INT UNSIGNED  NOT NULL,
  width                     INT UNSIGNED  NOT NULL,
  height                    INT UNSIGNED  NOT NULL,
  runtime_version           VARCHAR(32)   NOT NULL,
  source_version            INT UNSIGNED  NULL,
  created_at                DATETIME(3)   NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

  PRIMARY KEY (id),
  -- FK index (required) + serves the forward-compat "find instances of this source"
  -- query (MVP3 version-pinning) and the ON DELETE SET NULL lookup.
  KEY idx_mg_block_snapshots_source (source_motion_graphic_id),

  CONSTRAINT fk_mg_block_snapshots_source
    FOREIGN KEY (source_motion_graphic_id)
    REFERENCES motion_graphics(id)
    ON DELETE SET NULL
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;
