/**
 * Co-located styles for CastConfirmModal.
 *
 * Mirrors MusicBlockModal (panel / header-with-close / body sections) and uses the
 * same storyboardPageStyles tokens so the cast dialog matches the rest of the app.
 */
import type React from 'react';

import {
  BORDER,
  ERROR,
  PRIMARY,
  SUCCESS,
  SURFACE,
  SURFACE_ALT,
  SURFACE_ELEVATED,
  TEXT_PRIMARY,
  TEXT_SECONDARY,
} from './storyboardPageStyles';

const FONT = 'Inter, sans-serif';

export const castConfirmModalStyles = {
  backdrop: {
    position: 'fixed',
    inset: 0,
    zIndex: 1000,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'rgba(0, 0, 0, 0.45)',
  } as React.CSSProperties,
  panel: {
    width: 'min(560px, calc(100vw - 32px))',
    maxHeight: 'calc(100vh - 32px)',
    margin: 16,
    display: 'flex',
    flexDirection: 'column',
    overflow: 'hidden',
    background: SURFACE_ELEVATED,
    border: `1px solid ${BORDER}`,
    borderRadius: 8,
    color: TEXT_PRIMARY,
    fontFamily: FONT,
    outline: 'none',
  } as React.CSSProperties,
  header: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 12,
    padding: 16,
    borderBottom: `1px solid ${BORDER}`,
    flexShrink: 0,
  } as React.CSSProperties,
  titleGroup: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  } as React.CSSProperties,
  title: {
    margin: 0,
    fontSize: 16,
    lineHeight: '24px',
    fontWeight: 600,
    color: TEXT_PRIMARY,
  } as React.CSSProperties,
  subtitle: {
    margin: 0,
    color: TEXT_SECONDARY,
    fontSize: 12,
    lineHeight: '16px',
  } as React.CSSProperties,
  closeButton: {
    width: 32,
    height: 32,
    border: `1px solid ${BORDER}`,
    borderRadius: 8,
    background: SURFACE,
    color: TEXT_SECONDARY,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  } as React.CSSProperties,
  body: {
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    padding: 16,
    overflowY: 'auto',
  } as React.CSSProperties,
  // Generic body copy (progress / empty / failed states).
  message: {
    margin: 0,
    color: TEXT_SECONDARY,
    fontSize: 13,
    lineHeight: '20px',
  } as React.CSSProperties,
  // ── Category section (#1: Character references / Environment references) ──
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
  } as React.CSSProperties,
  sectionHeader: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  } as React.CSSProperties,
  sectionTitle: {
    margin: 0,
    fontSize: 12,
    lineHeight: '16px',
    fontWeight: 700,
    letterSpacing: '0.04em',
    textTransform: 'uppercase',
    color: TEXT_SECONDARY,
  } as React.CSSProperties,
  sectionCount: {
    fontSize: 11,
    fontWeight: 600,
    color: TEXT_SECONDARY,
    background: SURFACE,
    border: `1px solid ${BORDER}`,
    borderRadius: 999,
    padding: '1px 8px',
  } as React.CSSProperties,
  entryEditor: {
    display: 'flex',
    flexDirection: 'column',
    gap: 10,
    padding: 12,
    background: SURFACE,
    border: `1px solid ${BORDER}`,
    borderRadius: 8,
  } as React.CSSProperties,
  entryHeader: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'flex-end',
  } as React.CSSProperties,
  removeEntryButton: {
    border: `1px solid ${BORDER}`,
    borderRadius: 6,
    background: 'transparent',
    color: TEXT_SECONDARY,
    cursor: 'pointer',
    fontSize: 11,
    fontWeight: 600,
    fontFamily: FONT,
    padding: '2px 8px',
    lineHeight: '16px',
  } as React.CSSProperties,
  // Dashed "add another" affordance at the end of a category section.
  addEntryButton: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    minHeight: 36,
    border: `1px dashed ${BORDER}`,
    borderRadius: 8,
    background: 'transparent',
    color: TEXT_SECONDARY,
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 600,
    fontFamily: FONT,
  } as React.CSSProperties,
  field: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    minWidth: 0,
  } as React.CSSProperties,
  label: {
    color: TEXT_SECONDARY,
    fontSize: 12,
    lineHeight: '16px',
    fontWeight: 600,
  } as React.CSSProperties,
  input: {
    width: '100%',
    boxSizing: 'border-box',
    minHeight: 36,
    border: `1px solid ${BORDER}`,
    borderRadius: 8,
    background: SURFACE_ALT,
    color: TEXT_PRIMARY,
    padding: '0 10px',
    fontSize: 13,
    fontFamily: FONT,
    outline: 'none',
  } as React.CSSProperties,
  textarea: {
    width: '100%',
    boxSizing: 'border-box',
    minHeight: 64,
    resize: 'vertical',
    border: `1px solid ${BORDER}`,
    borderRadius: 8,
    background: SURFACE_ALT,
    color: TEXT_PRIMARY,
    padding: 10,
    fontSize: 13,
    lineHeight: '20px',
    fontFamily: FONT,
    outline: 'none',
  } as React.CSSProperties,
  overflowMessage: {
    margin: 0,
    padding: '8px 10px',
    background: SURFACE_ALT,
    border: `1px solid ${BORDER}`,
    borderRadius: 8,
    color: TEXT_SECONDARY,
    fontSize: 12,
    lineHeight: '16px',
  } as React.CSSProperties,
  estimate: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '10px 12px',
    background: SURFACE,
    border: `1px solid ${BORDER}`,
    borderRadius: 8,
    fontSize: 13,
    fontWeight: 600,
    color: TEXT_PRIMARY,
  } as React.CSSProperties,
  estimateAmount: {
    color: SUCCESS,
  } as React.CSSProperties,
  // Footer action row (sticky bottom).
  footer: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 10,
    padding: 16,
    borderTop: `1px solid ${BORDER}`,
    flexShrink: 0,
  } as React.CSSProperties,
  primaryButton: {
    height: 36,
    padding: '0 16px',
    border: 0,
    borderRadius: 8,
    background: PRIMARY,
    color: TEXT_PRIMARY,
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 600,
    fontFamily: FONT,
  } as React.CSSProperties,
  secondaryButton: {
    height: 36,
    padding: '0 16px',
    border: `1px solid ${BORDER}`,
    borderRadius: 8,
    background: SURFACE,
    color: TEXT_SECONDARY,
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 600,
    fontFamily: FONT,
  } as React.CSSProperties,
  error: {
    color: ERROR,
    fontSize: 12,
    lineHeight: '16px',
  } as React.CSSProperties,
} as const;
