import type React from 'react';

import {
  BORDER,
  ERROR,
  PRIMARY,
  PRIMARY_LIGHT,
  SUCCESS,
  SURFACE,
  SURFACE_ALT,
  SURFACE_ELEVATED,
  TEXT_PRIMARY,
  TEXT_SECONDARY,
} from './storyboardPageStyles';

export const musicBlockModalStyles = {
  backdrop: {
    position: 'fixed',
    inset: 0,
    zIndex: 100,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    background: 'rgba(0, 0, 0, 0.45)',
  } as React.CSSProperties,
  panel: {
    width: 'min(420px, calc(100vw - 32px))',
    maxHeight: 'calc(100vh - 32px)',
    margin: 16,
    overflow: 'auto',
    background: SURFACE_ELEVATED,
    border: `1px solid ${BORDER}`,
    borderRadius: 8,
    color: TEXT_PRIMARY,
    fontFamily: 'Inter, sans-serif',
  } as React.CSSProperties,
  header: {
    display: 'flex',
    alignItems: 'flex-start',
    gap: 12,
    padding: 16,
    borderBottom: `1px solid ${BORDER}`,
  } as React.CSSProperties,
  titleGroup: {
    flex: 1,
    minWidth: 0,
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
  } as React.CSSProperties,
  titleInput: {
    width: '100%',
    border: 0,
    outline: 'none',
    background: 'transparent',
    color: TEXT_PRIMARY,
    fontSize: 16,
    lineHeight: '24px',
    fontWeight: 600,
  } as React.CSSProperties,
  rangeText: {
    color: TEXT_SECONDARY,
    fontSize: 12,
    lineHeight: '16px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  } as React.CSSProperties,
  closeButton: {
    width: 32,
    height: 32,
    border: `1px solid ${BORDER}`,
    borderRadius: 8,
    background: SURFACE,
    color: TEXT_SECONDARY,
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  } as React.CSSProperties,
  body: {
    display: 'flex',
    flexDirection: 'column',
    gap: 12,
    padding: 16,
  } as React.CSSProperties,
  segmented: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: 4,
    padding: 4,
    background: SURFACE,
    border: `1px solid ${BORDER}`,
    borderRadius: 8,
  } as React.CSSProperties,
  segment: {
    minHeight: 32,
    border: 0,
    borderRadius: 4,
    background: 'transparent',
    color: TEXT_SECONDARY,
    cursor: 'pointer',
    fontSize: 12,
    lineHeight: '16px',
    fontWeight: 600,
  } as React.CSSProperties,
  segmentActive: {
    minHeight: 32,
    border: 0,
    borderRadius: 4,
    background: PRIMARY_LIGHT,
    color: TEXT_PRIMARY,
    cursor: 'pointer',
    fontSize: 12,
    lineHeight: '16px',
    fontWeight: 600,
  } as React.CSSProperties,
  field: {
    display: 'flex',
    flexDirection: 'column',
    gap: 4,
    minWidth: 0,
  } as React.CSSProperties,
  label: {
    color: TEXT_SECONDARY,
    fontSize: 12,
    lineHeight: '16px',
    fontWeight: 600,
  } as React.CSSProperties,
  input: {
    width: '100%',
    minHeight: 36,
    border: `1px solid ${BORDER}`,
    borderRadius: 8,
    background: SURFACE,
    color: TEXT_PRIMARY,
    padding: '0 10px',
    fontSize: 13,
  } as React.CSSProperties,
  textarea: {
    width: '100%',
    minHeight: 88,
    resize: 'vertical',
    border: `1px solid ${BORDER}`,
    borderRadius: 8,
    background: SURFACE,
    color: TEXT_PRIMARY,
    padding: 10,
    fontSize: 13,
    lineHeight: '20px',
  } as React.CSSProperties,
  planSummary: {
    minHeight: 28,
    display: 'flex',
    alignItems: 'center',
    padding: '0 10px',
    border: `1px solid ${BORDER}`,
    borderRadius: 8,
    background: SURFACE_ALT,
    color: TEXT_SECONDARY,
    fontSize: 12,
  } as React.CSSProperties,
  rangeGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: 8,
  } as React.CSSProperties,
  sceneLane: {
    display: 'grid',
    gridAutoFlow: 'column',
    gridAutoColumns: 'minmax(16px, 1fr)',
    gap: 4,
    height: 16,
    alignItems: 'center',
  } as React.CSSProperties,
  sceneLaneItem: {
    height: 8,
    borderRadius: 4,
    background: BORDER,
  } as React.CSSProperties,
  sceneLaneItemActive: {
    height: 8,
    borderRadius: 4,
    background: SUCCESS,
  } as React.CSSProperties,
  primaryButton: {
    height: 36,
    border: 0,
    borderRadius: 8,
    background: PRIMARY,
    color: TEXT_PRIMARY,
    cursor: 'pointer',
    fontSize: 13,
    fontWeight: 600,
  } as React.CSSProperties,
  error: {
    color: ERROR,
    fontSize: 12,
    lineHeight: '16px',
  } as React.CSSProperties,
} as const;
