import type React from 'react';

import {
  BORDER,
  PRIMARY,
  PRIMARY_LIGHT,
  SUCCESS,
  SURFACE,
  SURFACE_ELEVATED,
  TEXT_PRIMARY,
  TEXT_SECONDARY,
} from './nodeStyles';

export const musicBlockNodeStyles = {
  root: {
    width: '220px',
    background: SURFACE_ELEVATED,
    border: `1.5px solid ${BORDER}`,
    borderRadius: '8px',
    color: TEXT_PRIMARY,
    fontFamily: 'Inter, sans-serif',
    position: 'relative',
    userSelect: 'none',
    overflow: 'hidden',
  } as React.CSSProperties,
  rootActive: {
    borderColor: SUCCESS,
    boxShadow: `0 0 0 1px ${SUCCESS}`,
  } as React.CSSProperties,
  header: {
    display: 'flex',
    alignItems: 'center',
    gap: '8px',
    padding: '8px 12px',
    borderBottom: `1px solid ${BORDER}`,
  } as React.CSSProperties,
  glyph: {
    width: '24px',
    height: '24px',
    borderRadius: '4px',
    background: PRIMARY_LIGHT,
    color: SUCCESS,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  } as React.CSSProperties,
  title: {
    minWidth: 0,
    flex: 1,
    fontSize: '11px',
    lineHeight: '16px',
    fontWeight: 600,
    textTransform: 'uppercase',
    color: TEXT_PRIMARY,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  } as React.CSSProperties,
  body: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    padding: '8px 12px 12px',
  } as React.CSSProperties,
  metaRow: {
    display: 'flex',
    alignItems: 'center',
    gap: '4px',
    flexWrap: 'wrap',
  } as React.CSSProperties,
  badge: {
    display: 'inline-flex',
    alignItems: 'center',
    minWidth: 0,
    maxWidth: '100%',
    height: '22px',
    borderRadius: '4px',
    border: `1px solid ${BORDER}`,
    background: SURFACE,
    padding: '0 8px',
    color: TEXT_SECONDARY,
    fontSize: '10px',
    lineHeight: '14px',
    fontWeight: 600,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  } as React.CSSProperties,
  range: {
    margin: 0,
    fontSize: '12px',
    lineHeight: '16px',
    color: TEXT_SECONDARY,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  } as React.CSSProperties,
  previewBar: {
    height: '6px',
    borderRadius: '4px',
    background: `linear-gradient(90deg, ${SUCCESS}, ${PRIMARY})`,
  } as React.CSSProperties,
} as const;
