import type React from 'react';

import {
  BORDER,
  dialogStyle,
  ERROR,
  PRIMARY,
  SURFACE_ALT,
  SURFACE_ELEVATED,
  TEXT_PRIMARY,
  TEXT_SECONDARY,
  WARNING,
} from './SceneModal.styles';

export const step3Styles = {
  dialog: {
    ...dialogStyle,
    width: 'min(560px, calc(100vw - 32px))',
  },
  body: {
    display: 'flex',
    flexDirection: 'column',
    gap: 16,
    padding: 20,
    overflowY: 'auto',
  },
  section: {
    display: 'flex',
    flexDirection: 'column',
    gap: 8,
  },
  optionButton: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-start',
    gap: 4,
    width: '100%',
    padding: 12,
    border: `1px solid ${BORDER}`,
    borderRadius: 8,
    background: SURFACE_ALT,
    color: TEXT_PRIMARY,
    fontFamily: 'Inter, sans-serif',
    cursor: 'pointer',
    textAlign: 'left',
  },
  optionTitle: {
    fontSize: 14,
    lineHeight: '20px',
    fontWeight: 600,
  },
  optionDescription: {
    fontSize: 12,
    lineHeight: '18px',
    color: TEXT_SECONDARY,
  },
  label: {
    fontSize: 12,
    lineHeight: '18px',
    color: TEXT_SECONDARY,
    fontWeight: 500,
    textTransform: 'uppercase',
  },
  select: {
    width: '100%',
    height: 38,
    border: `1px solid ${BORDER}`,
    borderRadius: 8,
    background: SURFACE_ALT,
    color: TEXT_PRIMARY,
    fontFamily: 'Inter, sans-serif',
    fontSize: 14,
    padding: '0 10px',
  },
  durationNote: {
    margin: 0,
    padding: '8px 10px',
    border: `1px solid ${BORDER}`,
    borderRadius: 8,
    background: SURFACE_ALT,
    color: TEXT_SECONDARY,
    fontSize: 12,
    lineHeight: '18px',
  },
  durationNoteWarning: {
    margin: 0,
    padding: '8px 10px',
    border: `1px solid ${BORDER}`,
    borderRadius: 8,
    background: SURFACE_ALT,
    color: WARNING,
    fontSize: 12,
    lineHeight: '18px',
  },
  checkboxRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    minHeight: 28,
    fontSize: 14,
    lineHeight: '20px',
    color: TEXT_PRIMARY,
  },
  muted: {
    margin: 0,
    fontSize: 13,
    lineHeight: '18px',
    color: TEXT_SECONDARY,
  },
  error: {
    margin: 0,
    fontSize: 13,
    lineHeight: '18px',
    color: ERROR,
  },
  footer: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: 8,
    padding: '14px 20px',
    borderTop: `1px solid ${BORDER}`,
    background: SURFACE_ELEVATED,
  },
  secondaryButton: {
    height: 36,
    padding: '0 14px',
    border: `1px solid ${BORDER}`,
    borderRadius: 8,
    background: SURFACE_ALT,
    color: TEXT_PRIMARY,
    fontFamily: 'Inter, sans-serif',
    cursor: 'pointer',
  },
  primaryButton: {
    height: 36,
    padding: '0 14px',
    border: 0,
    borderRadius: 8,
    background: PRIMARY,
    color: '#FFFFFF',
    fontFamily: 'Inter, sans-serif',
    cursor: 'pointer',
  },
  primaryButtonDisabled: {
    height: 36,
    padding: '0 14px',
    border: 0,
    borderRadius: 8,
    background: PRIMARY,
    color: '#FFFFFF',
    fontFamily: 'Inter, sans-serif',
    cursor: 'not-allowed',
    opacity: 0.5,
  },
} satisfies Record<string, React.CSSProperties>;
