-- Migration: 021_files
-- Creates the `files` root table — the single source of truth for every
-- user-owned blob in the system (uploaded media, AI-generated outputs, etc.).
-- Replaces the project-scoped `project_assets_current` table as the canonical
-- blob identity: files are user-owned first, then optionally linked to projects
-- or drafts via pivot tables (migrations 022).
--
-- Column notes:
--   file_id      — UUID v4, generated by the application layer.
--   user_id      — owning user; FK to users.user_id ON DELETE CASCADE.
--   kind         — broad media kind; drives client-side rendering decisions.
--   storage_uri  — s3://<bucket>/<key> or r2://<bucket>/<key>; never a presigned URL.
--   mime_type    — set on finalization via S3 HEAD; nullable until then.
--   bytes        — raw byte count; set on finalization.
--   width/height — pixel dimensions for image/video; NULL for audio/document.
--   duration_ms  — media duration in milliseconds; NULL for images/documents.
--   display_name — user-visible label; defaults to the sanitized filename supplied
--                  at upload-URL creation time.
--   status       — lifecycle: pending → processing → ready | error.
--
-- Idempotent: CREATE TABLE IF NOT EXISTS is safe to run multiple times.
--
-- Manual rollback:
--   DROP TABLE IF EXISTS files;

CREATE TABLE IF NOT EXISTS files (
  file_id       CHAR(36)        NOT NULL,
  user_id       CHAR(36)        NOT NULL,
  kind          ENUM(
                  'video',
                  'audio',
                  'image',
                  'document',
                  'other'
                )               NOT NULL,
  storage_uri   VARCHAR(2048)   NOT NULL,
  mime_type     VARCHAR(128)    NULL,
  bytes         BIGINT UNSIGNED NULL,
  width         INT UNSIGNED    NULL,
  height        INT UNSIGNED    NULL,
  duration_ms   INT UNSIGNED    NULL,
  display_name  VARCHAR(255)    NULL,
  status        ENUM(
                  'pending',
                  'processing',
                  'ready',
                  'error'
                )               NOT NULL DEFAULT 'pending',
  error_message TEXT            NULL,
  created_at    DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at    DATETIME(3)     NOT NULL DEFAULT CURRENT_TIMESTAMP(3)
                                ON UPDATE CURRENT_TIMESTAMP(3),

  PRIMARY KEY (file_id),
  INDEX idx_files_user_status  (user_id, status),
  INDEX idx_files_user_created (user_id, created_at DESC),

  CONSTRAINT fk_files_user
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;
