-- Migration: 031_storyboard_blocks
-- Creates the `storyboard_blocks` table — the individual scene nodes (and the
-- special START/END sentinel nodes) that live on a user's storyboard canvas.
-- Each block belongs to exactly one generation_draft, identified by draft_id.
--
-- Column notes:
--   id           — UUID v4, generated by the application layer.
--   draft_id     — FK to generation_drafts.id; the storyboard identity.
--   block_type   — 'start' and 'end' are singleton sentinels per draft;
--                  'scene' blocks are the user-editable creative units.
--   name         — user-visible label (e.g. "SCENE 01"); NULL until set.
--   prompt       — scene-level text prompt sent to the AI generator; NULL until set.
--   duration_s   — scene duration in whole seconds; default 5.
--   position_x   — canvas X coordinate (React Flow logical units).
--   position_y   — canvas Y coordinate (React Flow logical units).
--   sort_order   — integer ordering used for "add block" insertion logic.
--   style        — kebab-case visual style slug (e.g. "cyberpunk"); NULL = no style.
--   created_at   — set on insert.
--   updated_at   — updated automatically on every row change.
--
-- Idempotent: uses CREATE TABLE IF NOT EXISTS.
--
-- Manual rollback:
--   DROP TABLE IF EXISTS storyboard_blocks;

CREATE TABLE IF NOT EXISTS storyboard_blocks (
  id           CHAR(36)       NOT NULL,
  draft_id     CHAR(36)       NOT NULL,
  block_type   ENUM(
                 'start',
                 'end',
                 'scene'
               )              NOT NULL,
  name         VARCHAR(255)   NULL,
  prompt       TEXT           NULL,
  duration_s   SMALLINT       NOT NULL DEFAULT 5,
  position_x   FLOAT          NOT NULL DEFAULT 0,
  position_y   FLOAT          NOT NULL DEFAULT 0,
  sort_order   INT            NOT NULL DEFAULT 0,
  style        VARCHAR(64)    NULL,
  created_at   TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
                              ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (id),
  KEY idx_storyboard_blocks_draft_id (draft_id),

  CONSTRAINT fk_storyboard_blocks_draft
    FOREIGN KEY (draft_id)
    REFERENCES generation_drafts(id)
    ON DELETE CASCADE
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;
