-- Migration: 032_storyboard_edges
-- Creates the `storyboard_edges` table — the directed connections between blocks
-- on the storyboard canvas. Each edge links a source block (exit port) to a
-- target block (entry port).
--
-- Uniqueness invariants enforced at the DB level:
--   uq_storyboard_edges_source — each block can have at most one exit edge.
--   uq_storyboard_edges_target — each block can have at most one entry edge.
--   These constraints mirror the one-in/one-out topology rule of the canvas.
--   The PUT /storyboards/:draftId full-replace endpoint deletes all edges before
--   re-inserting, so these constraints only apply during the INSERT phase of
--   that transaction.
--
-- Column notes:
--   id                — UUID v4, generated by the application layer.
--   draft_id          — denormalised draft reference; enables fast bulk delete
--                       of all edges for a draft without joining through blocks.
--   source_block_id   — the block from which the edge departs.
--   target_block_id   — the block at which the edge arrives.
--
-- Idempotent: uses CREATE TABLE IF NOT EXISTS.
--
-- Manual rollback:
--   DROP TABLE IF EXISTS storyboard_edges;

CREATE TABLE IF NOT EXISTS storyboard_edges (
  id                CHAR(36)   NOT NULL,
  draft_id          CHAR(36)   NOT NULL,
  source_block_id   CHAR(36)   NOT NULL,
  target_block_id   CHAR(36)   NOT NULL,

  PRIMARY KEY (id),

  -- One-in / one-out invariant enforced at DB level
  UNIQUE KEY uq_storyboard_edges_source (source_block_id),
  UNIQUE KEY uq_storyboard_edges_target (target_block_id),

  KEY idx_storyboard_edges_draft_id (draft_id),

  CONSTRAINT fk_storyboard_edges_draft
    FOREIGN KEY (draft_id)
    REFERENCES generation_drafts(id)
    ON DELETE CASCADE,

  CONSTRAINT fk_storyboard_edges_source
    FOREIGN KEY (source_block_id)
    REFERENCES storyboard_blocks(id)
    ON DELETE CASCADE,

  CONSTRAINT fk_storyboard_edges_target
    FOREIGN KEY (target_block_id)
    REFERENCES storyboard_blocks(id)
    ON DELETE CASCADE
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;
