-- Migration: 033_storyboard_block_media
-- Creates the `storyboard_block_media` table — the many-to-many pivot that
-- attaches files (images, videos, or audio clips) to storyboard scene blocks.
-- The application layer controls sort_order for the up-to-3 visible thumbnails
-- displayed on each SceneBlockNode on the canvas.
--
-- Column notes:
--   id          — UUID v4, generated by the application layer.
--   block_id    — FK to storyboard_blocks.id; the owning scene block.
--   file_id     — FK to files.file_id; the attached media file.
--   media_type  — broad media kind of the attached file ('image', 'video', 'audio').
--   sort_order  — controls display order within a block; lowest first.
--
-- Idempotent: uses CREATE TABLE IF NOT EXISTS.
--
-- Manual rollback:
--   DROP TABLE IF EXISTS storyboard_block_media;

CREATE TABLE IF NOT EXISTS storyboard_block_media (
  id          CHAR(36)   NOT NULL,
  block_id    CHAR(36)   NOT NULL,
  file_id     CHAR(36)   NOT NULL,
  media_type  ENUM(
                'image',
                'video',
                'audio'
              )          NOT NULL,
  sort_order  INT        NOT NULL DEFAULT 0,

  PRIMARY KEY (id),
  KEY idx_storyboard_block_media_block_id (block_id),

  CONSTRAINT fk_storyboard_block_media_block
    FOREIGN KEY (block_id)
    REFERENCES storyboard_blocks(id)
    ON DELETE CASCADE,

  CONSTRAINT fk_storyboard_block_media_file
    FOREIGN KEY (file_id)
    REFERENCES files(file_id)
    ON DELETE CASCADE
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;
