-- Migration: 035_scene_templates
-- Creates the `scene_templates` table — reusable scene blueprints that users
-- can save to their Library and later apply to new storyboard blocks.
--
-- Column notes:
--   id           — UUID v4, generated by the application layer.
--   user_id      — FK to users.user_id; the owning user.
--   name         — user-visible template name (e.g. "Intro Fade").
--   prompt       — scene-level text prompt for the AI generator.
--   duration_s   — intended scene duration in whole seconds.
--   style        — kebab-case visual style slug (e.g. "cyberpunk"); NULL = none.
--   deleted_at   — NULL = active; non-NULL = soft-deleted. All queries filter
--                  WHERE deleted_at IS NULL unless explicitly including deleted rows.
--   created_at   — set on insert.
--   updated_at   — updated automatically on every row change.
--
-- Idempotent: uses CREATE TABLE IF NOT EXISTS.
--
-- Manual rollback:
--   DROP TABLE IF EXISTS scene_templates;

CREATE TABLE IF NOT EXISTS scene_templates (
  id           CHAR(36)       NOT NULL,
  user_id      VARCHAR(255)   NOT NULL,
  name         VARCHAR(255)   NOT NULL,
  prompt       TEXT           NOT NULL,
  duration_s   SMALLINT       NOT NULL DEFAULT 5,
  style        VARCHAR(64)    NULL,
  deleted_at   TIMESTAMP      NULL     DEFAULT NULL,
  created_at   TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at   TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP
                              ON UPDATE CURRENT_TIMESTAMP,

  PRIMARY KEY (id),
  KEY idx_scene_templates_user_id (user_id),

  CONSTRAINT fk_scene_templates_user
    FOREIGN KEY (user_id)
    REFERENCES users(user_id)
    ON DELETE CASCADE
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;
