-- Migration: 036_scene_template_media
-- Creates the `scene_template_media` table — the many-to-many pivot that
-- attaches files (images, videos, or audio clips) to scene templates.
-- Mirrors the structure of storyboard_block_media.
--
-- Column notes:
--   id           — UUID v4, generated by the application layer.
--   template_id  — FK to scene_templates.id; the owning template.
--   file_id      — FK to files.file_id; the attached media file.
--   media_type   — broad media kind ('image', 'video', 'audio').
--   sort_order   — controls display order within a template; lowest first.
--
-- Constraint: each template may have at most 6 media items (enforced at the
-- service layer — no DB-level CHECK to remain compatible with MySQL < 8.0.16).
--
-- Idempotent: uses CREATE TABLE IF NOT EXISTS.
--
-- Manual rollback:
--   DROP TABLE IF EXISTS scene_template_media;

CREATE TABLE IF NOT EXISTS scene_template_media (
  id           CHAR(36)   NOT NULL,
  template_id  CHAR(36)   NOT NULL,
  file_id      CHAR(36)   NOT NULL,
  media_type   ENUM(
                 'image',
                 'video',
                 'audio'
               )          NOT NULL,
  sort_order   INT        NOT NULL DEFAULT 0,

  PRIMARY KEY (id),
  KEY idx_scene_template_media_template_id (template_id),

  CONSTRAINT fk_scene_template_media_template
    FOREIGN KEY (template_id)
    REFERENCES scene_templates(id)
    ON DELETE CASCADE,

  CONSTRAINT fk_scene_template_media_file
    FOREIGN KEY (file_id)
    REFERENCES files(file_id)
    ON DELETE CASCADE
) ENGINE=InnoDB
  DEFAULT CHARSET=utf8mb4
  COLLATE=utf8mb4_unicode_ci;
