import type { RowDataPacket } from 'mysql2/promise';

import type { FileKind } from '@ai-video-editor/project-schema';

import { pool } from '@/db/connection.js';

// Re-export so existing imports of FileKind from this module continue to work.
export type { FileKind };

/**
 * Lifecycle status for a file row.
 * `pending`   → presigned URL issued, upload not yet confirmed.
 * `processing` → finalize called, ingest job running.
 * `ready`     → ingest complete, metadata populated.
 * `error`     → ingest failed.
 */
export type FileStatus = 'pending' | 'processing' | 'ready' | 'error';

/** Full `files` row as returned by the repository. */
export type FileRow = {
  fileId: string;
  userId: string;
  kind: FileKind;
  storageUri: string;
  mimeType: string | null;
  bytes: number | null;
  width: number | null;
  height: number | null;
  /** Duration in milliseconds (for video/audio). Null for images/documents. */
  durationMs: number | null;
  displayName: string | null;
  status: FileStatus;
  errorMessage: string | null;
  createdAt: Date;
  updatedAt: Date;
  /** Null means the file is active; non-null means it has been soft-deleted. */
  deletedAt: Date | null;
  /** S3/R2 URI of the thumbnail frame generated by the ingest worker. Null when not yet generated. */
  thumbnailUri: string | null;
};

/** Parameters for inserting a new `pending` file row. */
type CreatePendingParams = {
  fileId: string;
  userId: string;
  kind: FileKind;
  storageUri: string;
  mimeType: string;
  displayName: string;
};

/** Parameters for finalizing a file (status → processing). */
type FinalizeParams = {
  fileId: string;
  mimeType: string;
};

/** Parameters written back by the ingest worker after FFprobe completes. */
export type ProbeMetadataParams = {
  fileId: string;
  durationMs: number | null;
  width: number | null;
  height: number | null;
  bytes: number | null;
};

// ── Internal row type ─────────────────────────────────────────────────────────

type DbRow = RowDataPacket & {
  file_id: string;
  user_id: string;
  kind: FileKind;
  storage_uri: string;
  mime_type: string | null;
  bytes: string | number | null;
  width: number | null;
  height: number | null;
  duration_ms: number | null;
  display_name: string | null;
  status: FileStatus;
  error_message: string | null;
  created_at: Date;
  updated_at: Date;
  deleted_at: Date | null;
  thumbnail_uri: string | null;
};

function mapRow(row: DbRow): FileRow {
  return {
    fileId: row.file_id,
    userId: row.user_id,
    kind: row.kind,
    storageUri: row.storage_uri,
    mimeType: row.mime_type,
    bytes: row.bytes == null ? null : Number(row.bytes),
    width: row.width,
    height: row.height,
    durationMs: row.duration_ms,
    displayName: row.display_name,
    status: row.status,
    errorMessage: row.error_message,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    deletedAt: row.deleted_at ?? null,
    thumbnailUri: row.thumbnail_uri ?? null,
  };
}

// ── Write operations ──────────────────────────────────────────────────────────

/** Inserts a `pending` file row. Called immediately after the presigned URL is issued. */
export async function createPending(params: CreatePendingParams): Promise<void> {
  await pool.execute(
    `INSERT INTO files
       (file_id, user_id, kind, storage_uri, mime_type, display_name)
     VALUES (?, ?, ?, ?, ?, ?)`,
    [
      params.fileId,
      params.userId,
      params.kind,
      params.storageUri,
      params.mimeType,
      params.displayName,
    ],
  );
}

/**
 * Transitions a file from `pending` → `processing` and sets the resolved mime_type.
 * Silent no-op when `file_id` does not match (the service checks existence first).
 */
export async function finalize(params: FinalizeParams): Promise<void> {
  await pool.execute(
    `UPDATE files SET status = 'processing', mime_type = ? WHERE file_id = ?`,
    [params.mimeType, params.fileId],
  );
}

/**
 * Writes FFprobe metadata back to the file row and marks it `ready`.
 * Called by the ingest worker after probing completes.
 */
export async function updateProbeMetadata(params: ProbeMetadataParams): Promise<void> {
  await pool.execute(
    `UPDATE files
     SET status = 'ready',
         duration_ms = ?,
         width = ?,
         height = ?,
         bytes = ?,
         error_message = NULL
     WHERE file_id = ?`,
    [params.durationMs, params.width, params.height, params.bytes, params.fileId],
  );
}

/** Writes the S3/R2 URI of the thumbnail generated by the ingest worker to the `files` row. */
export async function setThumbnailUri(fileId: string, uri: string | null): Promise<void> {
  await pool.execute(
    'UPDATE files SET thumbnail_uri = ? WHERE file_id = ?',
    [uri, fileId],
  );
}

/** Sets the file status to `error` with a message. Called by the ingest worker on failure. */
export async function setFileError(fileId: string, message: string): Promise<void> {
  await pool.execute(
    `UPDATE files SET status = 'error', error_message = ? WHERE file_id = ?`,
    [message, fileId],
  );
}

/**
 * Soft-deletes a file by setting `deleted_at` to the current timestamp.
 * Subsequent calls to `findById` / `findByIdForUser` will return null.
 * Returns true when a row was updated, false when `fileId` was not found.
 */
export async function softDelete(fileId: string): Promise<boolean> {
  const [result] = await pool.execute<import('mysql2/promise').ResultSetHeader>(
    'UPDATE files SET deleted_at = NOW(3) WHERE file_id = ? AND deleted_at IS NULL',
    [fileId],
  );
  return result.affectedRows > 0;
}

/**
 * Restores a soft-deleted file by clearing `deleted_at`.
 * Returns true when a row was updated, false when `fileId` was not found or was
 * not soft-deleted.
 */
export async function restore(fileId: string): Promise<boolean> {
  const [result] = await pool.execute<import('mysql2/promise').ResultSetHeader>(
    'UPDATE files SET deleted_at = NULL WHERE file_id = ? AND deleted_at IS NOT NULL',
    [fileId],
  );
  return result.affectedRows > 0;
}

// ── Read operations ───────────────────────────────────────────────────────────

/**
 * Returns a single non-deleted file row by its primary key, or null when not
 * found or soft-deleted. Use `findByIdIncludingDeleted` when you need to inspect
 * or restore a soft-deleted row.
 */
export async function findById(fileId: string): Promise<FileRow | null> {
  const [rows] = await pool.execute<DbRow[]>(
    'SELECT * FROM files WHERE file_id = ? AND deleted_at IS NULL',
    [fileId],
  );
  return rows.length ? mapRow(rows[0]!) : null;
}

/**
 * Returns a file row regardless of its soft-delete state.
 * Intended only for internal restore/admin paths — not re-exported from barrels.
 */
export async function findByIdIncludingDeleted(fileId: string): Promise<FileRow | null> {
  const [rows] = await pool.execute<DbRow[]>(
    'SELECT * FROM files WHERE file_id = ?',
    [fileId],
  );
  return rows.length ? mapRow(rows[0]!) : null;
}

/** Returns a non-deleted file only if it exists AND belongs to `userId`. Null otherwise. */
export async function findByIdForUser(fileId: string, userId: string): Promise<FileRow | null> {
  const [rows] = await pool.execute<DbRow[]>(
    'SELECT * FROM files WHERE file_id = ? AND user_id = ? AND deleted_at IS NULL',
    [fileId, userId],
  );
  return rows.length ? mapRow(rows[0]!) : null;
}

// ── List helpers (extracted to file.repository.list.ts to keep this file ≤ 300 lines) ──

export type {
  FileMimePrefix,
  FileTotalsRow,
} from './file.repository.list.js';

export {
  findReadyForUser,
  findAllForUser,
  getReadyTotalsForUser,
} from './file.repository.list.js';
