/**
 * Repository for the AI Motion Graphic feature — raw `mysql2`, no ORM.
 *
 * Three tables (data-model.md + ADR-0008/0009/0010):
 *   - motion_graphics                 — the aggregate-root, code-as-TEXT graphic.
 *   - motion_graphic_chat_turns       — append-only, app-assigned `seq` chat history.
 *   - motion_graphic_block_snapshots  — the immutable frozen copy attached to a block.
 *
 * Plus the storyboard_block_media pivot (existing, extended by migration 061) for the
 * attach path.
 *
 * Design decisions:
 * - The application generates UUIDs (`randomUUID()` at the call site); the repo accepts ids.
 * - List is owner-scoped: WHERE user_id=? AND deleted_at IS NULL ORDER BY updated_at DESC
 *   (index idx_motion_graphics_user_active). Keyset cursor on (updated_at, id) DESC.
 * - Chat read uses idx_mg_chat_turns_graphic_seq: WHERE motion_graphic_id=? ORDER BY seq.
 * - append assigns the next monotonic seq via MAX(seq)+1 (0 for the first turn).
 * - The snapshot+block-media insert runs in one transaction (pool.getConnection +
 *   begin/commit/rollback) — both rows or neither (ADR-0009). The snapshot is a frozen
 *   COPY: nothing references the live graphic, so source edits never touch it (AC-10).
 * - NO authorization / NotFoundError / ready-state gating here — that is the service (T6).
 *
 * Pattern mirrors generation-flow.repository.ts / storyboard.repository.ts: pool.execute,
 * RowDataPacket row types, camelCase result mapping.
 */
import { randomUUID } from 'node:crypto';
import type { PoolConnection, ResultSetHeader, RowDataPacket } from 'mysql2/promise';
import { pool } from '@/db/connection.js';

// ── Public types ──────────────────────────────────────────────────────────────

export type MotionGraphicStatus = 'generating' | 'ready' | 'failed';
export type ChatTurnRole = 'user' | 'assistant';
export type ChatTurnOutcome = 'ready' | 'failed';

/** Full motion_graphics record as returned by the repository. */
export type MotionGraphicRecord = {
  id: string;
  userId: string;
  title: string;
  code: string | null;
  propsSchema: unknown | null;
  durationSeconds: number;
  fps: number;
  width: number;
  height: number;
  runtimeVersion: string;
  status: MotionGraphicStatus;
  version: number;
  createdAt: Date;
  updatedAt: Date;
  deletedAt: Date | null;
};

/** A single chat turn. */
export type ChatTurnRecord = {
  id: string;
  motionGraphicId: string;
  role: ChatTurnRole;
  seq: number;
  content: string;
  generatedCode: string | null;
  outcome: ChatTurnOutcome | null;
  errorMessage: string | null;
  createdAt: Date;
};

/** A graphic read together with its chat turns in seq order. */
export type MotionGraphicWithChat = {
  graphic: MotionGraphicRecord;
  turns: ChatTurnRecord[];
};

/** The immutable snapshot row. */
export type BlockSnapshotRecord = {
  id: string;
  sourceMotionGraphicId: string | null;
  code: string;
  propsSchema: unknown | null;
  durationSeconds: number;
  fps: number;
  width: number;
  height: number;
  runtimeVersion: string;
  sourceVersion: number | null;
  createdAt: Date;
};

/** A storyboard_block_media row joined to its motion_graphic snapshot. */
export type BlockMediaSnapshotRecord = {
  mediaId: string;
  blockId: string;
  fileId: string | null;
  mediaType: 'image' | 'video' | 'audio' | 'motion_graphic';
  sortOrder: number;
  snapshot: BlockSnapshotRecord;
};

// ── Params ──────────────────────────────────────────────────────────────────

export type InsertMotionGraphicParams = {
  id: string;
  userId: string;
  title: string;
  durationSeconds: number;
  /** Optional overrides — defaults applied by the DB column DEFAULTs. */
  code?: string | null;
  propsSchema?: unknown | null;
  fps?: number;
  width?: number;
  height?: number;
  runtimeVersion?: string;
  status?: MotionGraphicStatus;
};

export type ListMotionGraphicsParams = {
  userId: string;
  limit: number;
  /** Opaque keyset cursor from a prior page's `nextCursor`. */
  cursor?: string | null;
};

export type ListMotionGraphicsResult = {
  items: MotionGraphicRecord[];
  nextCursor: string | null;
};

export type AppendChatTurnParams = {
  motionGraphicId: string;
  role: ChatTurnRole;
  content: string;
  generatedCode?: string | null;
  outcome?: ChatTurnOutcome | null;
  errorMessage?: string | null;
  /** Optional app-supplied id; generated by the DB-call when absent is NOT supported —
   *  the application owns id generation, so callers pass it. Optional for convenience. */
  id?: string;
};

export type InsertBlockSnapshotWithMediaParams = {
  snapshotId: string;
  mediaId: string;
  blockId: string;
  sourceMotionGraphicId: string | null;
  code: string;
  propsSchema?: unknown | null;
  durationSeconds: number;
  fps: number;
  width: number;
  height: number;
  runtimeVersion: string;
  sourceVersion?: number | null;
  sortOrder: number;
};

// ── Internal row types ────────────────────────────────────────────────────────

type MotionGraphicRow = RowDataPacket & {
  id: string;
  user_id: string;
  title: string;
  code: string | null;
  props_schema: unknown | null;
  duration_seconds: string | number;
  fps: number;
  width: number;
  height: number;
  runtime_version: string;
  status: MotionGraphicStatus;
  version: number;
  created_at: Date;
  updated_at: Date;
  deleted_at: Date | null;
};

type ChatTurnRow = RowDataPacket & {
  id: string;
  motion_graphic_id: string;
  role: ChatTurnRole;
  seq: number;
  content: string;
  generated_code: string | null;
  outcome: ChatTurnOutcome | null;
  error_message: string | null;
  created_at: Date;
};

type JoinedMediaRow = RowDataPacket & {
  media_id: string;
  block_id: string;
  file_id: string | null;
  media_type: 'image' | 'video' | 'audio' | 'motion_graphic';
  sort_order: number;
  snap_id: string;
  snap_source_motion_graphic_id: string | null;
  snap_code: string;
  snap_props_schema: unknown | null;
  snap_duration_seconds: string | number;
  snap_fps: number;
  snap_width: number;
  snap_height: number;
  snap_runtime_version: string;
  snap_source_version: number | null;
  snap_created_at: Date;
};

// ── Mappers ─────────────────────────────────────────────────────────────────

/** mysql2 may return a JSON column pre-parsed or as a raw string — handle both. */
function parseJson(value: unknown): unknown | null {
  if (value === null || value === undefined) return null;
  if (typeof value === 'string') {
    try {
      return JSON.parse(value);
    } catch {
      return value;
    }
  }
  return value;
}

function mapGraphic(row: MotionGraphicRow): MotionGraphicRecord {
  return {
    id: row.id,
    userId: row.user_id,
    title: row.title,
    code: row.code ?? null,
    propsSchema: parseJson(row.props_schema),
    durationSeconds: Number(row.duration_seconds),
    fps: row.fps,
    width: row.width,
    height: row.height,
    runtimeVersion: row.runtime_version,
    status: row.status,
    version: row.version,
    createdAt: row.created_at,
    updatedAt: row.updated_at,
    deletedAt: row.deleted_at ?? null,
  };
}

function mapTurn(row: ChatTurnRow): ChatTurnRecord {
  return {
    id: row.id,
    motionGraphicId: row.motion_graphic_id,
    role: row.role,
    seq: row.seq,
    content: row.content,
    generatedCode: row.generated_code ?? null,
    outcome: row.outcome ?? null,
    errorMessage: row.error_message ?? null,
    createdAt: row.created_at,
  };
}

const GRAPHIC_COLS = `id, user_id, title, code, props_schema, duration_seconds, fps,
  width, height, runtime_version, status, version, created_at, updated_at, deleted_at`;

// ── Cursor helpers (keyset on updated_at DESC, id DESC) ──────────────────────

function encodeCursor(updatedAt: Date, id: string): string {
  return Buffer.from(`${updatedAt.getTime()}:${id}`, 'utf8').toString('base64url');
}

function decodeCursor(cursor: string): { updatedAtMs: number; id: string } | null {
  try {
    const decoded = Buffer.from(cursor, 'base64url').toString('utf8');
    const idx = decoded.indexOf(':');
    if (idx < 0) return null;
    const updatedAtMs = Number(decoded.slice(0, idx));
    const id = decoded.slice(idx + 1);
    if (!Number.isFinite(updatedAtMs) || !id) return null;
    return { updatedAtMs, id };
  } catch {
    return null;
  }
}

// ── insertMotionGraphic (AC-01) ──────────────────────────────────────────────

export async function insertMotionGraphic(
  params: InsertMotionGraphicParams,
): Promise<MotionGraphicRecord> {
  const {
    id, userId, title, durationSeconds,
    code = null, propsSchema = null,
    fps, width, height, runtimeVersion, status,
  } = params;

  await pool.execute<ResultSetHeader>(
    `INSERT INTO motion_graphics
       (id, user_id, title, code, props_schema, duration_seconds,
        fps, width, height, runtime_version, status)
     VALUES (?, ?, ?, ?, ?, ?,
        COALESCE(?, DEFAULT(fps)),
        COALESCE(?, DEFAULT(width)),
        COALESCE(?, DEFAULT(height)),
        COALESCE(?, DEFAULT(runtime_version)),
        COALESCE(?, DEFAULT(status)))`,
    [
      id, userId, title, code,
      propsSchema === null ? null : JSON.stringify(propsSchema),
      durationSeconds,
      fps ?? null, width ?? null, height ?? null,
      runtimeVersion ?? null, status ?? null,
    ],
  );

  const record = await readGraphicByPk(id);
  if (!record) throw new Error(`motion_graphics row not found after insert: ${id}`);
  return record;
}

/** Internal PK read (no owner filter — owner scope is the service's concern). */
async function readGraphicByPk(id: string): Promise<MotionGraphicRecord | null> {
  const [rows] = await pool.execute<MotionGraphicRow[]>(
    `SELECT ${GRAPHIC_COLS} FROM motion_graphics WHERE id = ? LIMIT 1`,
    [id],
  );
  return rows.length ? mapGraphic(rows[0]!) : null;
}

// ── findMotionGraphicWithChat ────────────────────────────────────────────────

/**
 * Reads one graphic by PK plus its chat turns in seq order
 * (index idx_mg_chat_turns_graphic_seq). Returns null when the graphic is absent.
 */
export async function findMotionGraphicWithChat(
  id: string,
): Promise<MotionGraphicWithChat | null> {
  const graphic = await readGraphicByPk(id);
  if (!graphic) return null;

  const [turnRows] = await pool.execute<ChatTurnRow[]>(
    `SELECT id, motion_graphic_id, role, seq, content, generated_code,
            outcome, error_message, created_at
       FROM motion_graphic_chat_turns
      WHERE motion_graphic_id = ?
      ORDER BY seq ASC`,
    [id],
  );
  return { graphic, turns: turnRows.map(mapTurn) };
}

// ── listMotionGraphicsByOwner (AC-13) ────────────────────────────────────────

/**
 * Lists a user's non-deleted graphics newest-first, cursor-paged.
 * Owner-scoped + soft-delete filtered, served by idx_motion_graphics_user_active.
 * Keyset cursor on (updated_at, id) DESC for a stable page boundary.
 */
export async function listMotionGraphicsByOwner(
  params: ListMotionGraphicsParams,
): Promise<ListMotionGraphicsResult> {
  const { userId, limit, cursor } = params;
  // Over-fetch one row to detect a next page. LIMIT is inlined as a validated integer:
  // mysql2's binary prepared protocol rejects a bound `LIMIT ?` (ER_WRONG_ARGUMENTS) —
  // matches the inline-LIMIT idiom used elsewhere in the repo layer.
  const safeLimit = Math.max(1, Math.floor(limit));
  const fetch = safeLimit + 1;

  const decoded = cursor ? decodeCursor(cursor) : null;

  let rows: MotionGraphicRow[];
  if (decoded) {
    [rows] = await pool.execute<MotionGraphicRow[]>(
      `SELECT ${GRAPHIC_COLS}
         FROM motion_graphics
        WHERE user_id = ? AND deleted_at IS NULL
          AND (updated_at < ? OR (updated_at = ? AND id < ?))
        ORDER BY updated_at DESC, id DESC
        LIMIT ${fetch}`,
      [userId, new Date(decoded.updatedAtMs), new Date(decoded.updatedAtMs), decoded.id],
    );
  } else {
    [rows] = await pool.execute<MotionGraphicRow[]>(
      `SELECT ${GRAPHIC_COLS}
         FROM motion_graphics
        WHERE user_id = ? AND deleted_at IS NULL
        ORDER BY updated_at DESC, id DESC
        LIMIT ${fetch}`,
      [userId],
    );
  }

  const hasMore = rows.length > safeLimit;
  const pageRows = hasMore ? rows.slice(0, safeLimit) : rows;
  const items = pageRows.map(mapGraphic);

  let nextCursor: string | null = null;
  if (hasMore && items.length > 0) {
    const last = items[items.length - 1]!;
    nextCursor = encodeCursor(last.updatedAt, last.id);
  }

  return { items, nextCursor };
}

// ── updateMotionGraphicCode (AC-06/AC-14 success path) ───────────────────────

/**
 * Sets `code`, flips status to 'ready', and bumps `version` on a successful generation.
 * Returns true when a row was updated.
 */
export async function updateMotionGraphicCode(params: {
  id: string;
  code: string;
}): Promise<boolean> {
  const [result] = await pool.execute<ResultSetHeader>(
    `UPDATE motion_graphics
        SET code = ?, status = 'ready', version = version + 1, updated_at = NOW(3)
      WHERE id = ?`,
    [params.code, params.id],
  );
  return result.affectedRows > 0;
}

// ── renameMotionGraphic (AC-01) ──────────────────────────────────────────────

export async function renameMotionGraphic(id: string, title: string): Promise<boolean> {
  const [result] = await pool.execute<ResultSetHeader>(
    `UPDATE motion_graphics SET title = ?, updated_at = NOW(3) WHERE id = ?`,
    [title, id],
  );
  return result.affectedRows > 0;
}

// ── appendChatTurn (AC-03/AC-14) ─────────────────────────────────────────────

/**
 * Appends a chat turn with the next app-assigned `seq` (MAX(seq)+1, 0 for the first).
 * The seq is computed in the INSERT … SELECT so a single statement assigns it.
 */
export async function appendChatTurn(
  params: AppendChatTurnParams,
): Promise<ChatTurnRecord> {
  const {
    motionGraphicId, role, content,
    generatedCode = null, outcome = null, errorMessage = null,
  } = params;
  const id = params.id ?? randomUUID();

  await pool.execute<ResultSetHeader>(
    `INSERT INTO motion_graphic_chat_turns
       (id, motion_graphic_id, role, seq, content, generated_code, outcome, error_message)
     SELECT ?, ?, ?,
            COALESCE(MAX(seq) + 1, 0), ?, ?, ?, ?
       FROM motion_graphic_chat_turns
      WHERE motion_graphic_id = ?`,
    [id, motionGraphicId, role, content, generatedCode, outcome, errorMessage, motionGraphicId],
  );

  const [rows] = await pool.execute<ChatTurnRow[]>(
    `SELECT id, motion_graphic_id, role, seq, content, generated_code,
            outcome, error_message, created_at
       FROM motion_graphic_chat_turns
      WHERE id = ?
      LIMIT 1`,
    [id],
  );
  if (!rows.length) throw new Error(`chat turn not found after insert: ${id}`);
  return mapTurn(rows[0]!);
}

// ── copyChatTurns (AC-12) ────────────────────────────────────────────────────

/**
 * Copies every chat turn from `sourceId` to `targetId`, preserving seq order and each
 * turn's generated_code — the duplicate is seeded with live, re-runnable turns (AC-12).
 * New ids are assigned per copied turn; `seq` is preserved verbatim from the source.
 * Returns the number of turns copied.
 */
export async function copyChatTurns(params: {
  sourceId: string;
  targetId: string;
}): Promise<number> {
  const { sourceId, targetId } = params;

  const [result] = await pool.execute<ResultSetHeader>(
    `INSERT INTO motion_graphic_chat_turns
       (id, motion_graphic_id, role, seq, content, generated_code, outcome, error_message)
     SELECT UUID(), ?, role, seq, content, generated_code, outcome, error_message
       FROM motion_graphic_chat_turns
      WHERE motion_graphic_id = ?
      ORDER BY seq ASC`,
    [targetId, sourceId],
  );
  return result.affectedRows;
}

// ── insertBlockSnapshotWithMedia (AC-04/AC-10) ───────────────────────────────

/**
 * Atomically inserts an immutable motion_graphic_block_snapshots row AND a
 * storyboard_block_media row referencing it (media_type='motion_graphic',
 * file_id=NULL, motion_graphic_snapshot_id=<snapshot>) in one transaction (ADR-0009).
 *
 * The snapshot stores a frozen COPY of code/duration/geometry — nothing references the
 * live graphic, so later edits to the source never alter the snapshot (AC-10).
 * Both rows are written or neither.
 */
export async function insertBlockSnapshotWithMedia(
  params: InsertBlockSnapshotWithMediaParams,
): Promise<{ snapshotId: string; mediaId: string }> {
  const {
    snapshotId, mediaId, blockId, sourceMotionGraphicId,
    code, propsSchema = null, durationSeconds,
    fps, width, height, runtimeVersion, sourceVersion = null, sortOrder,
  } = params;

  const conn: PoolConnection = await pool.getConnection();
  try {
    await conn.beginTransaction();

    await conn.execute<ResultSetHeader>(
      `INSERT INTO motion_graphic_block_snapshots
         (id, source_motion_graphic_id, code, props_schema, duration_seconds,
          fps, width, height, runtime_version, source_version)
       VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
      [
        snapshotId, sourceMotionGraphicId, code,
        propsSchema === null ? null : JSON.stringify(propsSchema),
        durationSeconds, fps, width, height, runtimeVersion, sourceVersion,
      ],
    );

    await conn.execute<ResultSetHeader>(
      `INSERT INTO storyboard_block_media
         (id, block_id, file_id, motion_graphic_snapshot_id, media_type, sort_order)
       VALUES (?, ?, NULL, ?, 'motion_graphic', ?)`,
      [mediaId, blockId, snapshotId, sortOrder],
    );

    await conn.commit();
    return { snapshotId, mediaId };
  } catch (err) {
    await conn.rollback();
    throw err;
  } finally {
    conn.release();
  }
}

// ── findBlockMediaSnapshot ───────────────────────────────────────────────────

/**
 * Reads a storyboard_block_media row joined to its motion_graphic snapshot
 * (index idx_storyboard_block_media_mg_snapshot). Returns null when the media row is
 * absent or has no snapshot. No owner filter — scope lives in the service.
 */
export async function findBlockMediaSnapshot(
  mediaId: string,
): Promise<BlockMediaSnapshotRecord | null> {
  const [rows] = await pool.execute<JoinedMediaRow[]>(
    `SELECT m.id            AS media_id,
            m.block_id      AS block_id,
            m.file_id       AS file_id,
            m.media_type    AS media_type,
            m.sort_order    AS sort_order,
            s.id                       AS snap_id,
            s.source_motion_graphic_id AS snap_source_motion_graphic_id,
            s.code                     AS snap_code,
            s.props_schema             AS snap_props_schema,
            s.duration_seconds         AS snap_duration_seconds,
            s.fps                      AS snap_fps,
            s.width                    AS snap_width,
            s.height                   AS snap_height,
            s.runtime_version          AS snap_runtime_version,
            s.source_version           AS snap_source_version,
            s.created_at               AS snap_created_at
       FROM storyboard_block_media m
       JOIN motion_graphic_block_snapshots s
         ON s.id = m.motion_graphic_snapshot_id
      WHERE m.id = ?
      LIMIT 1`,
    [mediaId],
  );
  if (!rows.length) return null;
  const r = rows[0]!;
  return {
    mediaId: r.media_id,
    blockId: r.block_id,
    fileId: r.file_id ?? null,
    mediaType: r.media_type,
    sortOrder: r.sort_order,
    snapshot: {
      id: r.snap_id,
      sourceMotionGraphicId: r.snap_source_motion_graphic_id ?? null,
      code: r.snap_code,
      propsSchema: parseJson(r.snap_props_schema),
      durationSeconds: Number(r.snap_duration_seconds),
      fps: r.snap_fps,
      width: r.snap_width,
      height: r.snap_height,
      runtimeVersion: r.snap_runtime_version,
      sourceVersion: r.snap_source_version ?? null,
      createdAt: r.snap_created_at,
    },
  };
}
